# Site settings
title: Less Color Utility
email: scott.keller13@gmail.com
description: "This utility allows you to run the Less color functions in browser, quickly."
baseurl: "/jsfiddles-less-color-util"
url: "http://sskeller.github.io"

# Build settings
markdown: kramdown
permalink: pretty
